version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MqttService"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16mf70uukyjyc"
s3_prefix = "MqttService"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
